### PR TITLE
Add configurable endpoints for AWS services.

### PR DESCRIPTION
**Pull request by dmarkey**
This allows facilities like localstack to run this lambda. This is just to demonstrate the changes, please give me time to test that this works OK.

### CODE REVIEW

**Comment by dmarkey** [comment]
```
{
    "TagSet": [
        {
            "Key": "av-signature",
            "Value": "OK"
        },
        {
            "Key": "av-status",
            "Value": "CLEAN"
        },
        {
            "Key": "av-timestamp",
            "Value": "2021/05/20 21:06:30 UTC"
        }
    ]
}
```

Works fine on Localstack (docker executer), and tested the updater function also - with an SNS notification.

**Comment by dmarkey** [comment]
Will check on actual AWS tomorrow.

**Comment by dmarkey** [comment]
Tested on AWS:

Signature updater function ✅ 
S3 Event + tagging of result ✅ 
Publishing to SNS ✅ 
I haven't used `scan_bucket` or `display_infected` before but I'm 100% sure they'll work with the changes.

**Review by jdepp — APPROVED** [review]

**Comment by jdepp** [comment]
@dmarkey Looks great, and thanks for the PR! 🚀

**Comment by dmarkey** [comment]
No probs! Who can merge?

**Comment by jdepp** [comment]
@dmarkey Apologies, just saw this, I merged it in. Thanks again!

**Pull request merged**
