### PR TITLE
Python3 Support

### PR DESCRIPTION
**Pull request by smellman**
Fixes for supports Python3.

- includes fixes from #71 
- docker container uses pip3
- fixes with scope in test code for Python3
- fixes decode issue

### CODE REVIEW

**Comment by smellman** [comment]
@jaygorrell Can you review my PR?

**Comment by chrisgilmerproj** [comment]
@jaygorrell - should we tag this as v2.0.0 and start doing releases? It might actually help us in the future to have these tags for folks doing development.

**Comment by jaygorrell** [comment]
I think so, yeah - feel free to push that if you have a moment.

**Comment by chrisgilmerproj** [comment]
Done!

**Comment by chrisgilmerproj** [comment]
I tested this against #100 and was able to prove everything worked with `make scan` and `make update`. Nice job @smellman!

**Pull request merged**
