### PR TITLE
Add functionality to post to SNS upon start of scan

### PR DESCRIPTION
**Pull request by jfurmankiewiczupgrade**
When the lambda creates a listener to the S3 event,  it is not possible for any other lambda or SNS topic to listen to the same event.

Hence, there is no way to notify the downstream system *as soon as the file is uploaded* (so that it knows the file is in S3 and is about to go through virus scanning). This is important for user experience in UI dashboard to provide detailed status to file uploaders.

This PR adds 2 additional environment variables

* AV_SCAN_START_SNS_ARN: optional SNS ARN to publish message upon start of scan 
* AV_SCAN_START_METADATA: metadata field name to indicate scan has started

### CODE REVIEW

**Comment by jfurmankiewiczupgrade** [comment]
Sample of a message sent upon file upload / scan start
```
{"av-scan-start": true, "bucket": "mycompany-upload-file-quarantine", "av-timestamp": "2018/02/24 23:16:23 UTC", "key": "doc.pdf"}
```

**Comment by jfurmankiewiczupgrade** [comment]
Hi, let me know if there is anything missing. Would love to get this merged into master, so we wouldn't need to deploy off a fork. Thanks!

**Comment by jfurmankiewiczupgrade** [comment]
Hi, following up on this...let me know if there is anything that needs to be changed or whether this is OK to merge to master?

Thanks!

**Comment by denniswebb** [comment]
Sorry.  Crazy few weeks.  Please sign the CLA, and I can merge this afternoon.
Thanks for the PR.

**Comment by jfurmankiewiczupgrade** [comment]
hi @denniswebb thank you for responding. I have actually signed the CLA, it's just waiting for review

**Comment by denniswebb** [comment]
@jaygorrell You know more about the CLA than I do.  It's saying not signed.  Can you check?

**Comment by jfurmankiewiczupgrade** [comment]
it says so when I click on the link again:

You have signed the CLA for upsidetravel/bucket-antivirus-function

**Comment by jfurmankiewiczupgrade** [comment]
I presume it's in a pending status and someone has to review it on your end

**Comment by jfurmankiewiczupgrade** [comment]
here it is
cla

**Comment by jaygorrell** [comment]
I see the signature in the DB so I'll go ahead and merge. It looks like there may be problems with the cla-assistant service.

**Comment by pravsingh** [comment]
this is awesome!
thanks Jacek for this one.

**Comment by jfurmankiewiczupgrade** [comment]
Still one left for review:
https://github.com/upsidetravel/bucket-antivirus-function/pull/22

**Pull request merged**
