### PR TITLE
Format the code with the black command line tool

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
@jaygorrell - This is a quick PR that uses the [black](https://pypi.org/project/black/) formatting tool on this library with default settings. Cleans up the code so that my linter stops complaining as I write code for this repo. I'll stop sneaking in linter fixes once this is in.

### CODE REVIEW

**Comment by jaygorrell** [comment]
@necaris would you mind taking a quick look at these? you're the python style guru :)

**Comment by necaris** [comment]
@jaygorrell looks like `black` being run with default options -- LGTM 😄

**Comment by jaygorrell** [comment]
Hah, thanks. I wasn't familiar with the multiline print stuff.

**Comment by chrisgilmerproj** [comment]
I think this addresses part of #74.

**Pull request merged**
